baseurl: http://govapi.github.io/
markdown: redcarpet
name: US Government APIs
exclude:
- go
- copy-template
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md

permalink: pretty

# Author/Organization info to be displayed in the templates
author:
  name: Gray Brooks
  url: https://pages.18f.gov/API-All-the-X/

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: GovAPI logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /
  internal: true
- text: Other Lists
  url: /other-lists/
  internal: false
- text: Other Lists
  url: /18f-list/
  internal: false
- text: How You Can Help
  url: /help/
  internal: false

repos:
- name: govapi.github.io
  description: Main repository
  url: https://github.com/govapi/govapi.github.io

# Style Variables
brand_color: "#1188ff"

google_analytics_ua: 
