baseurl: https://theunitedstates.io/APIs
markdown: redcarpet
name: US Government APIs
exclude:
- go
- copy-template
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md

permalink: pretty

# Author/Organization info to be displayed in the templates
author:
  name: Gray Brooks
  url: https://pages.18f.gov/API-All-the-X/

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/usflag.png
logoalt: US flag

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /
  internal: true
- text: 18F List
  url: 18f-list/
  internal: true
- text: Other Lists
  url: other-lists/
  internal: true
- text: How You Can Help
  url: help/
  internal: true

repos:
- name: APIs
  description: Main repository
  url: https://github.com/unitedstates/APIs

# Style Variables
brand_color: "#1188ff"
