baseurl: /
markdown: redcarpet
name: US Government APIs
exclude:
- go
- copy-template
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md

permalink: pretty

# Author/Organization info to be displayed in the templates
author:
  name: Gray Brooks
  url: https://pages.18f.gov/API-All-the-X/

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: GovAPI logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: Adding a New Page
  url: adding-a-new-page/
  internal: true
- text: Adding Images
  url: adding-images/
  internal: true
- text: Updating the Config File
  url: updating-the-config-file/
  internal: true
- text: GitHub Setup
  url: github-setup/
  internal: true
- text: Post Your Guide
  url: post-your-guide/
  internal: true

repos:
- name: govapi.github.io
  description: Main repository
  url: https://github.com/govapi/govapi.github.io

# Style Variables
brand_color: "#1188ff"

google_analytics_ua: 
